### ISSUE TITLE
1_crop_vehicle_img_from_vdo.py

### ISSUE THREAD

**Issue by WANGYYYYYYYYY** [didi/mtmc-vt#9]
1_crop_vehicle_img_from_vdo.py这个代码运行结束后，在哪里有生成裁剪好的图像呢？

**Comment by sisrfeng** [comment]
你在哪里找到裁剪好的图像啊？

**Comment by WANGYYYYYYYYY** [comment]
在第一个程序里，需要把一句话取消注释



---Original---

**Comment by sisrfeng** [comment]
# cv2.imwrite(out_path, cropped_img)是吧
你是逐行看，然后发现的？
作者为啥要注释掉呢

**Comment by WANGYYYYYYYYY** [comment]
方便交流，我们加个微信吧。19801297390



---Original---

**Comment by sisrfeng** [comment]
好的

**Comment by sisrfeng** [comment]
out_dir = "../aic19-track1-mtmc/adjust_c_cropped_imgs"
懂了，要先在aic19-track1-mtmc下面建立adjust_c_cropped_imgs文件夹
